
const CATS={"entradas":{label:"Entradas",icon:"🥗"},"pratos-principais":{label:"Pratos principais",icon:"🍲"},"sobremesas":{label:"Sobremesas",icon:"🍍"}};
const TAG_ICONS={peixe:'🐟',carne:'🥩',porco:'🐖',marisco:'🦐',vegetariano:'🥬',rápido:'⚡','sem forno':'🚫🔥',arroz:'🍚',asiático:'🍜',fruta:'🍊',família:'👨‍👩‍👧‍👦',portuguesa:'🇵🇹',espanhola:'🇪🇸'};
let recipes=[],selectedTags=new Set(),planner=new Set(),query='';let cook={recipe:null,index:0};
const $=s=>document.querySelector(s);const app=()=>$('#app');
function stars(n){return n? '⭐'.repeat(n)+' Miguelin':'Ainda por classificar';}
function norm(s){return (s||'').toString().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();}
function allTags(){return [...new Set(recipes.flatMap(r=>r.tags||[]))].sort((a,b)=>a.localeCompare(b,'pt'));}
function match(r){const hay=norm([r.title,r.category,r.intro,...r.ingredients,...r.steps,...(r.tags||[])].join(' '));const q=norm(query);const okQ=!q||hay.includes(q);const okT=[...selectedTags].every(t=>(r.tags||[]).includes(t)||r.category===t);return okQ&&okT;}
function iconFor(r){for(const t of r.tags||[]) if(TAG_ICONS[t]) return TAG_ICONS[t]; return CATS[r.category]?.icon||'🍽️';}
function render(){const hash=location.hash.replace('#','')||'home'; if(hash.startsWith('receita/')) return renderDetail(hash.split('/')[1]); if(hash==='adicionar') return renderAdd(); if(hash==='compras') return renderShopping(); return renderHome();}
function renderHome(){const filtered=recipes.filter(match);app().innerHTML=`<section class="hero"><div class="hero-card"><h1>Livro de Receitas do Miguel</h1><p>Repositório de receitas testadas, normalizadas e fáceis de consultar no telemóvel.</p></div><div class="stats"><div class="stat"><strong>${recipes.length}</strong>receitas</div><div class="stat"><strong>${allTags().length}</strong>filtros</div><div class="stat"><strong>${planner.size}</strong>na lista de compras</div></div></section><div class="wrap"><section class="panel"><div class="search-row"><input id="search" placeholder="Pesquisar por receita, ingrediente, tag ou preparação..." value="${query.replaceAll('"','&quot;')}"><button class="btn primary" id="clear">Limpar</button></div><div class="chips">${Object.entries(CATS).map(([k,c])=>`<button class="chip ${selectedTags.has(k)?'active':''}" data-tag="${k}">${c.icon} ${c.label}</button>`).join('')}${allTags().map(t=>`<button class="chip ${selectedTags.has(t)?'active':''}" data-tag="${t}">${TAG_ICONS[t]||'🏷️'} ${t}</button>`).join('')}</div></section><section class="sections">${Object.entries(CATS).map(([key,c])=>`<div class="section-col"><h2>${c.icon} ${c.label}</h2><div class="recipe-list">${filtered.filter(r=>r.category===key).map(card).join('')||'<p class="muted">Sem resultados.</p>'}</div></div>`).join('')}</section></div>`;bindHome();}
function card(r){return `<article class="recipe-card"><div class="photo-slot">${r.photo?`<img src="${r.photo}" alt="${r.title}">`:`${iconFor(r)} Foto futura`}</div><h3>${r.title}</h3><div class="meta"><span class="pill">${CATS[r.category].label}</span><span class="pill">${r.time}</span><span class="pill">${r.servings}</span><span class="pill">${stars(r.miguelin)}</span></div><p>${r.intro}</p><div class="tags">${(r.tags||[]).slice(0,5).map(t=>`<span class="tag">${TAG_ICONS[t]||''} ${t}</span>`).join('')}</div><div class="card-actions"><a class="btn primary" href="#receita/${r.id}">Ver receita</a><button class="btn" data-plan="${r.id}">${planner.has(r.id)?'Remover da lista':'Adicionar à lista'}</button></div></article>`}
function bindHome(){const search=$('#search');search?.addEventListener('input',e=>{query=e.target.value;renderHome();});$('#clear')?.addEventListener('click',()=>{query='';selectedTags.clear();renderHome();});document.querySelectorAll('[data-tag]').forEach(b=>b.onclick=()=>{const t=b.dataset.tag;selectedTags.has(t)?selectedTags.delete(t):selectedTags.add(t);renderHome();});document.querySelectorAll('[data-plan]').forEach(b=>b.onclick=()=>{planner.has(b.dataset.plan)?planner.delete(b.dataset.plan):planner.add(b.dataset.plan);savePlanner();renderHome();});}
function renderDetail(id){const r=recipes.find(x=>x.id===id); if(!r){location.hash='home';return} app().innerHTML=`<div class="wrap"><article class="detail"><a class="btn" href="#home">← Voltar</a><h2>${iconFor(r)} ${r.title}</h2><p>${r.intro}</p><div class="meta"><span class="pill">${CATS[r.category].label}</span><span class="pill">${r.time}</span><span class="pill">${r.servings}</span><span class="pill">${r.difficulty}</span><span class="pill">${stars(r.miguelin)}</span></div><div class="card-actions" style="margin-top:14px"><button class="btn primary" id="cook">Modo cozinhar</button><button class="btn" id="print">Imprimir / PDF</button><button class="btn" id="plan">${planner.has(r.id)?'Remover da lista de compras':'Adicionar à lista de compras'}</button></div><div class="detail-grid"><section><h3>Ingredientes</h3><ul class="list-check">${r.ingredients.map(i=>`<li>${i}</li>`).join('')}</ul><h3>Dicas</h3><ul>${r.tips.map(i=>`<li>${i}</li>`).join('')}</ul></section><section><h3>Preparação</h3>${r.steps.map((s,i)=>`<div class="step"><span class="step-num">${i+1}</span><span>${s}</span></div>`).join('')}</section></div></article></div>`;$('#print').onclick=()=>window.print();$('#plan').onclick=()=>{planner.has(r.id)?planner.delete(r.id):planner.add(r.id);savePlanner();renderDetail(id)};$('#cook').onclick=()=>startCook(r);}
function startCook(r){cook={recipe:r,index:0};drawCook()}function drawCook(){const r=cook.recipe;if(!r)return;const total=r.steps.length;document.body.insertAdjacentHTML('beforeend',`<div class="cook-mode" id="cookMode"><div class="cook-box"><p>${r.title} — passo ${cook.index+1}/${total}</p><div class="cook-step">${r.steps[cook.index]}</div><div class="cook-controls"><button class="btn" id="prevCook">Anterior</button><button class="btn primary" id="nextCook">${cook.index===total-1?'Terminar':'Seguinte'}</button><button class="btn" id="closeCook">Fechar</button></div></div></div>`);$('#prevCook').onclick=()=>{if(cook.index>0){$('#cookMode').remove();cook.index--;drawCook();}};$('#nextCook').onclick=()=>{if(cook.index<total-1){$('#cookMode').remove();cook.index++;drawCook();}else $('#cookMode').remove();};$('#closeCook').onclick=()=>$('#cookMode').remove();}
function renderShopping(){const chosen=recipes.filter(r=>planner.has(r.id));const merged={};chosen.forEach(r=>r.shopping.forEach(i=>merged[i]=(merged[i]||0)+1));app().innerHTML=`<div class="wrap"><section class="panel"><h1>Lista de compras combinada</h1><p>Escolhe receitas na página inicial e esta lista junta os ingredientes.</p><div class="card-actions"><a class="btn" href="#home">← Receitas</a><button class="btn primary" onclick="window.print()">Imprimir / PDF</button><button class="btn" id="copyShop">Copiar</button><button class="btn" id="clearPlan">Limpar lista</button></div></section><section class="detail"><h2>Receitas selecionadas</h2><p>${chosen.map(r=>r.title).join(', ')||'Nenhuma receita selecionada.'}</p><h2>Compras</h2><div class="shopping-output" id="shopText">${Object.keys(merged).sort((a,b)=>a.localeCompare(b,'pt')).map(i=>'☐ '+i).join('\n')||'Adiciona receitas à lista primeiro.'}</div></section></div>`;$('#copyShop').onclick=()=>navigator.clipboard.writeText($('#shopText').innerText);$('#clearPlan').onclick=()=>{planner.clear();savePlanner();renderShopping();};}
function renderAdd(){app().innerHTML=`<div class="wrap"><section class="form-card"><h1>Adicionar receita</h1><p>Preenche no PC, gera o bloco JSON e cola no ficheiro <strong>data/recipes.json</strong>. A edição direta no GitHub continua sempre possível.</p><div class="form-grid"><label>Nome<input id="fTitle"></label><label>Categoria<select id="fCat"><option value="entradas">Entradas</option><option value="pratos-principais">Pratos principais</option><option value="sobremesas">Sobremesas</option></select></label><label>Doses<input id="fServ" placeholder="Ex.: 4 pessoas"></label><label>Tempo<input id="fTime" placeholder="Ex.: 30 min"></label><label>Dificuldade<input id="fDiff" placeholder="Fácil / Médio / Difícil"></label><label>Estrelas Miguelin<select id="fMig"><option value="0">Ainda por classificar</option><option value="1">1 Miguelin</option><option value="2">2 Miguelin</option><option value="3">3 Miguelin</option><option value="4">4 Miguelin</option><option value="5">5 Miguelin</option></select></label></div><label>Resumo<input id="fIntro"></label><label>Ingredientes — uma linha por ingrediente<textarea id="fIng"></textarea></label><label>Preparação — um passo por linha<textarea id="fSteps"></textarea></label><label>Dicas — uma linha por dica<textarea id="fTips"></textarea></label><label>Lista de compras — uma linha por item<textarea id="fShop"></textarea></label><label>Tags/filtros — separados por vírgula<input id="fTags" placeholder="peixe, rápido, sem forno"></label><button class="btn primary" id="gen">Gerar JSON</button><button class="btn" id="copyJson">Copiar JSON</button><textarea class="codebox" id="out" readonly></textarea></section></div>`;$('#gen').onclick=genJson;$('#copyJson').onclick=()=>navigator.clipboard.writeText($('#out').value);}
function slug(s){return norm(s).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'nova-receita'}function lines(id){return $('#'+id).value.split('\n').map(x=>x.trim()).filter(Boolean)}
function genJson(){const o={id:slug($('#fTitle').value),title:$('#fTitle').value.trim(),category:$('#fCat').value,servings:$('#fServ').value.trim(),time:$('#fTime').value.trim(),difficulty:$('#fDiff').value.trim(),miguelin:Number($('#fMig').value),intro:$('#fIntro').value.trim(),ingredients:lines('fIng'),steps:lines('fSteps'),tips:lines('fTips'),shopping:lines('fShop'),tags:$('#fTags').value.split(',').map(x=>x.trim()).filter(Boolean),photo:''};$('#out').value=JSON.stringify(o,null,2)+',';}
function savePlanner(){localStorage.setItem('miguelRecipesPlanner',JSON.stringify([...planner]));}function loadPlanner(){try{planner=new Set(JSON.parse(localStorage.getItem('miguelRecipesPlanner')||'[]'))}catch(e){planner=new Set()}}
fetch('data/recipes.json').then(r=>r.json()).then(d=>{recipes=d;loadPlanner();render();});window.addEventListener('hashchange',render);
